#base   "../../_customizations/#alternatives/#enabled/payload race panel/resource/ui/objectivestatusescort.res"
#base   "../../_customizations/#customizations/#enabled/payload race panel v2/resource/ui/objectivestatusescort.res"
#base   "../../_customizations/#customizations/#enabled/payload race panel/resource/ui/objectivestatusescort.res"
#base	"../../_customizations/#alternatives/#enabled/payload panel/resource/ui/objectivestatusescort.res"
#base	"../../_customizations/_basefiles/objectivestatusescort.res"