#base   "../../_customizations/#alternatives/#enabled/payload race panel/resource/ui/objectivestatusescort.res"
#base   "../../_customizations/#customizations/#enabled/payload-race-v2-objectivestatusescort.res"
#base   "../../_customizations/#customizations/#enabled/payload race panel/resource/ui/objectivestatusescort.res"
#base	"../../_customizations/#alternatives/#enabled/objectivestatusescort.res"
#base	"../../_customizations/_basefiles/resource/ui/objectivestatusescort.res"