#base   "../_stream/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/more themed elements/scripts/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/buildings panel v2/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/cleaner buildings panels - alerts v2/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/centered mvm money/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/cleaner buildings panels/hudlayout.res"
#base	"../_customizations/#alternatives/#enabled/targetid/hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/transparent viewmodels/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/metal-xhair-hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/game timers/hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/lower-spectator-targetid-hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/targetid-oldest/hudlayout.res"
#base	"../_customizations/_basefiles/scripts/hudlayout.res"
