#base   "../_customizations/#customizations/#enabled/building alerts v2/scripts/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/centered mvm money/scripts/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/cleaner buildings panels/scripts/hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/streamer mode/scripts/hudlayout.res"
#base	"../_customizations/#alternatives/#enabled/targetid/scripts/hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/transparent viewmodels/scripts/hudlayout.res"
#base   "../_customizations/#customizations/#enabled/centered metal/scripts/hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/game timers/scripts/hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/lower spectator targetid/scripts/hudlayout.res"
#base   "../_customizations/#alternatives/#enabled/older targetid/scripts/hudlayout.res"
#base   "../_basetf2hud/scripts/hudlayout.res"
#base	"../_customizations/_basefiles/scripts/hudlayout.res"